"""create_multitenant_tables

Revision ID: 6a45e1afbe56
Revises: 0bc741a5a65c
Create Date: 2026-07-05 04:56:01.688590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a45e1afbe56'
down_revision: Union[str, Sequence[str], None] = '0bc741a5a65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='URL-safe unique identifier. Used in routing and future subdomains.'),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan', sa.String(length=32), server_default='free', nullable=False, comment='One of: free, pro, enterprise'),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False, comment='One of: active, suspended, deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_organizations_slug'),
    schema='public'
    )
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False, schema='public')
    op.create_index('ix_organizations_status', 'organizations', ['status'], unique=False, schema='public')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='The user who performed the action. NULL if system-initiated.'),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('action_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False, schema='public')
    op.create_index('ix_audit_logs_organization_id', 'audit_logs', ['organization_id'], unique=False, schema='public')
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False, schema='public')
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='member', nullable=False, comment='Role the invited user will receive on acceptance.'),
    sa.Column('token', sa.String(length=128), nullable=False, comment='One-time token sent in the invitation email.'),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False, comment='One of: pending, accepted, expired, revoked'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='UTC datetime when this invitation can no longer be accepted.'),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['public.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_invitations_token'),
    schema='public'
    )
    op.create_index('ix_invitations_email', 'invitations', ['email'], unique=False, schema='public')
    op.create_index('ix_invitations_organization_id', 'invitations', ['organization_id'], unique=False, schema='public')
    op.create_index('ix_invitations_status', 'invitations', ['status'], unique=False, schema='public')
    op.create_index('ix_invitations_token', 'invitations', ['token'], unique=False, schema='public')
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='member', nullable=False, comment='One of: owner, admin, member, guest'),
    sa.Column('invited_by', sa.UUID(), nullable=True, comment='User who sent the invitation. NULL if the org creator.'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['public.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_members_org_user'),
    schema='public'
    )
    op.create_index('ix_org_members_organization_id', 'organization_members', ['organization_id'], unique=False, schema='public')
    op.create_index('ix_org_members_role', 'organization_members', ['role'], unique=False, schema='public')
    op.create_index('ix_org_members_user_id', 'organization_members', ['user_id'], unique=False, schema='public')
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Tenant key. Every query MUST filter by this.'),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=32), server_default='private', nullable=False, comment='One of: public (org-wide), private (members only)'),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_workspaces_created_by', 'workspaces', ['created_by'], unique=False, schema='public')
    op.create_index('ix_workspaces_organization_id', 'workspaces', ['organization_id'], unique=False, schema='public')
    op.create_index('ix_workspaces_visibility', 'workspaces', ['visibility'], unique=False, schema='public')
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='viewer', nullable=False, comment='One of: owner, editor, viewer'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_members_ws_user'),
    schema='public'
    )
    op.create_index('ix_workspace_members_role', 'workspace_members', ['role'], unique=False, schema='public')
    op.create_index('ix_workspace_members_user_id', 'workspace_members', ['user_id'], unique=False, schema='public')
    op.create_index('ix_workspace_members_workspace_id', 'workspace_members', ['workspace_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_members_workspace_id', table_name='workspace_members', schema='public')
    op.drop_index('ix_workspace_members_user_id', table_name='workspace_members', schema='public')
    op.drop_index('ix_workspace_members_role', table_name='workspace_members', schema='public')
    op.drop_table('workspace_members', schema='public')
    op.drop_index('ix_workspaces_visibility', table_name='workspaces', schema='public')
    op.drop_index('ix_workspaces_organization_id', table_name='workspaces', schema='public')
    op.drop_index('ix_workspaces_created_by', table_name='workspaces', schema='public')
    op.drop_table('workspaces', schema='public')
    op.drop_index('ix_org_members_user_id', table_name='organization_members', schema='public')
    op.drop_index('ix_org_members_role', table_name='organization_members', schema='public')
    op.drop_index('ix_org_members_organization_id', table_name='organization_members', schema='public')
    op.drop_table('organization_members', schema='public')
    op.drop_index('ix_invitations_token', table_name='invitations', schema='public')
    op.drop_index('ix_invitations_status', table_name='invitations', schema='public')
    op.drop_index('ix_invitations_organization_id', table_name='invitations', schema='public')
    op.drop_index('ix_invitations_email', table_name='invitations', schema='public')
    op.drop_table('invitations', schema='public')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs', schema='public')
    op.drop_index('ix_audit_logs_organization_id', table_name='audit_logs', schema='public')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs', schema='public')
    op.drop_table('audit_logs', schema='public')
    op.drop_index('ix_organizations_status', table_name='organizations', schema='public')
    op.drop_index('ix_organizations_slug', table_name='organizations', schema='public')
    op.drop_table('organizations', schema='public')
    # ### end Alembic commands ###
