"""create_knowledge_management_tables

Revision ID: 87a48639f471
Revises: 6a45e1afbe56
Create Date: 2026-07-05 05:08:38.699242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a48639f471'
down_revision: Union[str, Sequence[str], None] = '6a45e1afbe56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), server_default='#6366F1', nullable=False, comment="Hex color code for tags (e.g., '#6366F1')"),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_tags_org_name'),
    schema='public'
    )
    op.create_index('ix_tags_organization_id', 'tags', ['organization_id'], unique=False, schema='public')
    op.create_table('folders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('parent_folder_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False, comment="Computed or materialized path hierarchy for rapid query (e.g. '/HR/Policies')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['public.folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_folders_organization_id', 'folders', ['organization_id'], unique=False, schema='public')
    op.create_index('ix_folders_parent_folder_id', 'folders', ['parent_folder_id'], unique=False, schema='public')
    op.create_index('ix_folders_workspace_id', 'folders', ['workspace_id'], unique=False, schema='public')
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=32), server_default='private', nullable=False, comment='One of: public, private'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_knowledge_bases_organization_id', 'knowledge_bases', ['organization_id'], unique=False, schema='public')
    op.create_index('ix_knowledge_bases_visibility', 'knowledge_bases', ['visibility'], unique=False, schema='public')
    op.create_index('ix_knowledge_bases_workspace_id', 'knowledge_bases', ['workspace_id'], unique=False, schema='public')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=2048), nullable=False, comment='Supabase Storage path within the bucket'),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False, comment='One of: pending, processing, processed, failed'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA-256 hash of the original file bytes to prevent duplication'),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['public.folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['public.knowledge_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['public.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_documents_checksum', 'documents', ['checksum'], unique=False, schema='public')
    op.create_index('ix_documents_folder_id', 'documents', ['folder_id'], unique=False, schema='public')
    op.create_index('ix_documents_knowledge_base_id', 'documents', ['knowledge_base_id'], unique=False, schema='public')
    op.create_index('ix_documents_organization_id', 'documents', ['organization_id'], unique=False, schema='public')
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False, schema='public')
    op.create_index('ix_documents_workspace_id', 'documents', ['workspace_id'], unique=False, schema='public')
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding_status', sa.String(length=32), server_default='pending', nullable=False, comment='One of: pending, processing, completed, failed'),
    sa.ForeignKeyConstraint(['document_id'], ['public.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False, schema='public')
    op.create_index('ix_document_chunks_embedding_status', 'document_chunks', ['embedding_status'], unique=False, schema='public')
    op.create_table('document_tags',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['public.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['public.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id'),
    sa.UniqueConstraint('document_id', 'tag_id', name='uq_document_tags_doc_tag'),
    schema='public'
    )
    op.create_index('ix_document_tags_document_id', 'document_tags', ['document_id'], unique=False, schema='public')
    op.create_index('ix_document_tags_tag_id', 'document_tags', ['tag_id'], unique=False, schema='public')
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=2048), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['public.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['public.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_document_versions_checksum', 'document_versions', ['checksum'], unique=False, schema='public')
    op.create_index('ix_document_versions_document_id', 'document_versions', ['document_id'], unique=False, schema='public')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_organization_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('invitations_organization_id_fkey'), 'invitations', type_='foreignkey')
    op.drop_constraint(op.f('invitations_invited_by_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'users', ['invited_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'invitations', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('organization_members_user_id_fkey'), 'organization_members', type_='foreignkey')
    op.drop_constraint(op.f('organization_members_organization_id_fkey'), 'organization_members', type_='foreignkey')
    op.drop_constraint(op.f('organization_members_invited_by_fkey'), 'organization_members', type_='foreignkey')
    op.create_foreign_key(None, 'organization_members', 'users', ['invited_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'organization_members', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'organization_members', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('workspace_members_user_id_fkey'), 'workspace_members', type_='foreignkey')
    op.drop_constraint(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_members', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_members', 'workspaces', ['workspace_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('workspaces_organization_id_fkey'), 'workspaces', type_='foreignkey')
    op.drop_constraint(op.f('workspaces_created_by_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'workspaces', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'workspaces', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_created_by_fkey'), 'workspaces', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('workspaces_organization_id_fkey'), 'workspaces', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'workspace_members', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'workspace_members', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('workspace_members_user_id_fkey'), 'workspace_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'organization_members', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'organization_members', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'organization_members', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('organization_members_invited_by_fkey'), 'organization_members', 'users', ['invited_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('organization_members_organization_id_fkey'), 'organization_members', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('organization_members_user_id_fkey'), 'organization_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'invitations', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'invitations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_invited_by_fkey'), 'invitations', 'users', ['invited_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('invitations_organization_id_fkey'), 'invitations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'audit_logs', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_organization_id_fkey'), 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_document_versions_document_id', table_name='document_versions', schema='public')
    op.drop_index('ix_document_versions_checksum', table_name='document_versions', schema='public')
    op.drop_table('document_versions', schema='public')
    op.drop_index('ix_document_tags_tag_id', table_name='document_tags', schema='public')
    op.drop_index('ix_document_tags_document_id', table_name='document_tags', schema='public')
    op.drop_table('document_tags', schema='public')
    op.drop_index('ix_document_chunks_embedding_status', table_name='document_chunks', schema='public')
    op.drop_index('ix_document_chunks_document_id', table_name='document_chunks', schema='public')
    op.drop_table('document_chunks', schema='public')
    op.drop_index('ix_documents_workspace_id', table_name='documents', schema='public')
    op.drop_index('ix_documents_status', table_name='documents', schema='public')
    op.drop_index('ix_documents_organization_id', table_name='documents', schema='public')
    op.drop_index('ix_documents_knowledge_base_id', table_name='documents', schema='public')
    op.drop_index('ix_documents_folder_id', table_name='documents', schema='public')
    op.drop_index('ix_documents_checksum', table_name='documents', schema='public')
    op.drop_table('documents', schema='public')
    op.drop_index('ix_knowledge_bases_workspace_id', table_name='knowledge_bases', schema='public')
    op.drop_index('ix_knowledge_bases_visibility', table_name='knowledge_bases', schema='public')
    op.drop_index('ix_knowledge_bases_organization_id', table_name='knowledge_bases', schema='public')
    op.drop_table('knowledge_bases', schema='public')
    op.drop_index('ix_folders_workspace_id', table_name='folders', schema='public')
    op.drop_index('ix_folders_parent_folder_id', table_name='folders', schema='public')
    op.drop_index('ix_folders_organization_id', table_name='folders', schema='public')
    op.drop_table('folders', schema='public')
    op.drop_index('ix_tags_organization_id', table_name='tags', schema='public')
    op.drop_table('tags', schema='public')
    # ### end Alembic commands ###
